/aruco_node:
  ros__parameters:
    marker_size: 0.0435
    aruco_dictionary_id: DICT_5X5_100
    image_topic: /image_raw
    camera_info_topic: /camera_info

follow_ball:
  ros__parameters:
    rcv_timeout_secs: 1.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.5
    max_size_thresh: 0.1
    filter_value: 0.9
